"""Fix column type for trainer_id in WorkoutPlan

Revision ID: 17b20217c710
Revises: 81a0bc8bd689
Create Date: 2024-08-12 00:28:34.911784

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '17b20217c710'
down_revision = '81a0bc8bd689'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_user_trainer_id',  # Constraint name
            'trainer',             # Referenced table
            ['trainer_id'],        # Columns in this table
            ['id']                 # Columns in referenced table
        )

    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_workout_plan_trainer_id',  # Constraint name
            'trainer',                     # Referenced table
            ['trainer_id'],                # Columns in this table
            ['id']                         # Columns in referenced table
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.drop_constraint('fk_workout_plan_trainer_id', type_='foreignkey')
        batch_op.drop_column('trainer_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_trainer_id', type_='foreignkey')
        batch_op.drop_column('trainer_id')

    # ### end Alembic commands ###
