"""Remove columns from user model

Revision ID: 398776069071
Revises: 17b20217c710
Create Date: 2024-08-12 14:55:28.158605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398776069071'
down_revision = '17b20217c710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_workout_plan')
    op.drop_table('trainer')
    with op.batch_alter_table('nutrition_plan', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('progress_tracking', schema=None) as batch_op:
        batch_op.alter_column('measurements',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_trainer_id', type_='foreignkey')
        batch_op.drop_column('trainer_id')
        batch_op.drop_column('nationality')
        batch_op.drop_column('description')
        batch_op.drop_column('hobbies')

    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint('fk_workout_plan_trainer_id', type_='foreignkey')
        batch_op.drop_column('trainer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_workout_plan_trainer_id', 'trainer', ['trainer_id'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hobbies', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('trainer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_trainer_id', 'trainer', ['trainer_id'], ['id'])

    with op.batch_alter_table('progress_tracking', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('measurements',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('nutrition_plan', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('trainer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('specialty', sa.VARCHAR(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_workout_plan',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('workout_plan_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plan.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workout_plan_id')
    )
    # ### end Alembic commands ###
